services:
  stargazing-spots:
    build:
      context: ./apps/stargazing_spots
      dockerfile: Dockerfile
    env_file: ./apps/stargazing_spots/.env
    volumes:
      - ./apps/stargazing_spots/input:/app/input
      - ./apps/stargazing_spots/output:/app/output
      - ./validation:/app/validation
    command: python -m stargazing_spots --all-regions --from-geojson input/portugal/osm/osm_features_portugal.geojson

  stargazing-spots-test:
    build:
      context: ./apps/stargazing_spots
      dockerfile: Dockerfile
    command: python -m pytest tests/ -v
    volumes:
      - ./apps/stargazing_spots/tests:/app/tests
